language: node_js

node_js:
    - "9"

branches:
    only:
        - master

git:
    submodules: false
  
before_install:
    - git submodule update --init --remote --recursive

script:
    - yarn test & yarn run build && yarn run deploy

notifications:
    email:
        on_success: never
        on_failure: always