language: node_js

node_js:
    - "9"

branches:
    only:
        - master

script:
    - yarn test & yarn run build && yarn run deploy

notifications:
    email:
        on_success: never
        on_failure: always